//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuNews.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lines {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lines() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OsuNews.Resources.Lines", typeof(Lines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NewVideoPostTitle {
            get {
                return ResourceManager.GetString("NewVideoPostTitle", resourceCulture);
            }
        }
        
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        internal static string NonStdMod {
            get {
                return ResourceManager.GetString("NonStdMod", resourceCulture);
            }
        }
        
        internal static string ForcedMods {
            get {
                return ResourceManager.GetString("ForcedMods", resourceCulture);
            }
        }
        
        internal static string CouldntAnalyze {
            get {
                return ResourceManager.GetString("CouldntAnalyze", resourceCulture);
            }
        }
        
        internal static string GandonSpotted {
            get {
                return ResourceManager.GetString("GandonSpotted", resourceCulture);
            }
        }
        
        internal static string UnableToDownloadPreview {
            get {
                return ResourceManager.GetString("UnableToDownloadPreview", resourceCulture);
            }
        }
        
        internal static string MapUploaded {
            get {
                return ResourceManager.GetString("MapUploaded", resourceCulture);
            }
        }
    }
}
